"""Video style catalog. Each style shapes the clip split, camera language and pacing of a video prompt."""

VIDEO_STYLES: list[dict] = [
    {
        "id": "cinematic_product",
        "name_fa": "نمایش سینمایی محصول",
        "name_en": "Cinematic product showcase",
        "description_fa": "نماهای نزدیک و آرام از محصول با نور دراماتیک؛ حس لوکس و باکیفیت.",
        "description_en": "Slow macro shots of the product with dramatic light; premium feel.",
        "beats": ["macro detail reveal", "product in hero light, slow orbit", "product in use, end on logo-free hero frame"],
        "camera": "macro 100mm and 50mm, slow dolly and orbit, shallow depth of field",
        "pacing": "slow, 1 continuous move per clip",
        "best_for": ["promo", "sales"],
    },
    {
        "id": "pov",
        "name_fa": "زاویه‌ی دید اول‌شخص (POV)",
        "name_en": "POV",
        "description_fa": "بیننده خودش را جای مشتری می‌بیند؛ «POV: اولین بار که…»",
        "description_en": "First-person view that puts the viewer in the customer's shoes.",
        "beats": ["hands enter frame, arriving", "first interaction with product/service", "reaction moment, satisfied hold"],
        "camera": "first-person head-height, 24mm, natural handheld",
        "pacing": "medium, natural",
        "best_for": ["promo", "educational"],
    },
    {
        "id": "before_after",
        "name_fa": "قبل و بعد",
        "name_en": "Before / after transformation",
        "description_fa": "مشکل، لحظه‌ی تغییر و نتیجه؛ مناسب خدمات و محصولاتی با نتیجه‌ی قابل‌دیدن.",
        "description_en": "Problem state, transformation moment, result.",
        "beats": ["the problem state, slightly desaturated", "the transformation action", "the result, brighter, same framing as clip 1"],
        "camera": "locked-off tripod, identical framing for before and after",
        "pacing": "medium, clear contrast",
        "best_for": ["promo", "sales", "educational"],
    },
    {
        "id": "tutorial_steps",
        "name_fa": "آموزش مرحله‌به‌مرحله",
        "name_en": "Step-by-step tutorial",
        "description_fa": "دست‌ها از بالا یا روبه‌رو یک کار را قدم‌به‌قدم انجام می‌دهند.",
        "description_en": "Top-down or front hands-only steps.",
        "beats": ["step 1 with tools laid out", "step 2", "final result presented"],
        "camera": "top-down 35mm, static, clean surface",
        "pacing": "clear, one step per clip",
        "best_for": ["educational"],
    },
    {
        "id": "ugc_testimonial",
        "name_fa": "ویدیوی کاربرمحور (UGC)",
        "name_en": "UGC-style testimonial",
        "description_fa": "یک مشتری معمولی با موبایل از تجربه‌اش حرف می‌زند؛ طبیعی و باورپذیر.",
        "description_en": "Casual selfie-style customer talking about their experience.",
        "beats": ["selfie greeting holding the product", "showing the product closer while talking", "smiling recommendation, hold"],
        "camera": "front phone camera look, arm's length, slight handheld",
        "pacing": "conversational",
        "best_for": ["promo", "sales"],
    },
    {
        "id": "day_in_life",
        "name_fa": "یک روز با ما",
        "name_en": "Day in the life / behind the scenes",
        "description_fa": "پشت صحنه‌ی کسب‌وکار؛ آماده‌سازی، کار روزانه، لحظه‌ی تحویل.",
        "description_en": "Behind the scenes of the business: prep, work, delivery.",
        "beats": ["opening the shop/workspace in morning light", "hands at work, craft detail", "handing the finished product to a customer"],
        "camera": "35mm handheld documentary, natural light",
        "pacing": "relaxed",
        "best_for": ["promo", "educational", "news"],
    },
    {
        "id": "asmr_detail",
        "name_fa": "جزئیات حسی (ASMR)",
        "name_en": "ASMR / sensory detail",
        "description_fa": "صداها و بافت‌های نزدیک؛ ریختن، بریدن، بازکردن بسته.",
        "description_en": "Close sensory textures: pouring, cutting, unboxing sounds.",
        "beats": ["extreme close texture", "satisfying action close-up", "final still close-up"],
        "camera": "macro, locked-off, very shallow focus",
        "pacing": "slow, satisfying",
        "best_for": ["promo"],
    },
    {
        "id": "unboxing",
        "name_fa": "آنباکسینگ",
        "name_en": "Unboxing",
        "description_fa": "بازکردن بسته‌بندی و دیدن محصول برای اولین بار.",
        "description_en": "Opening the package and revealing the product.",
        "beats": ["closed package on table, hands enter", "opening and first reveal", "product held up to camera, hold"],
        "camera": "top-down then 45° angle, 35mm",
        "pacing": "medium, building to the reveal",
        "best_for": ["promo", "sales"],
    },
    {
        "id": "myth_vs_fact",
        "name_fa": "باور غلط و واقعیت",
        "name_en": "Myth vs fact",
        "description_fa": "یک باور رایج را نشان می‌دهد و بعد واقعیت را؛ عالی برای محتوای آموزشی.",
        "description_en": "Show a common misconception, then the truth.",
        "beats": ["person doing it the common wrong way", "pause, realisation", "doing it the right way, better result"],
        "camera": "medium shot 50mm, static",
        "pacing": "medium with a clear pause beat",
        "best_for": ["educational"],
    },
    {
        "id": "problem_solution",
        "name_fa": "مشکل و راه‌حل",
        "name_en": "Problem → solution",
        "description_fa": "یک مشکل آشنا برای مخاطب، بعد محصول به‌عنوان راه‌حل.",
        "description_en": "A relatable pain point, then the product as the fix.",
        "beats": ["frustrated moment with the problem", "discovering the product", "relieved, problem solved, hold"],
        "camera": "medium 35mm, slow push-in on the solution",
        "pacing": "fast hook, calmer resolution",
        "best_for": ["sales", "promo"],
    },
    {
        "id": "stop_motion",
        "name_fa": "استاپ‌موشن",
        "name_en": "Stop-motion style",
        "description_fa": "اشیا خودشان جابه‌جا می‌شوند؛ بامزه و چشم‌گیر.",
        "description_en": "Objects move by themselves in playful stop-motion.",
        "beats": ["objects assemble themselves on a surface", "product appears in the arrangement", "final tidy flat-lay, hold"],
        "camera": "top-down, locked-off, stop-motion frame feel",
        "pacing": "snappy",
        "best_for": ["promo", "educational"],
    },
    {
        "id": "news_explainer",
        "name_fa": "خبر و توضیح",
        "name_en": "News explainer",
        "description_fa": "یک خبر یا ترند مرتبط با حوزه‌ی کاری را کوتاه و تصویری توضیح می‌دهد.",
        "description_en": "Visually explains an industry news item or trend.",
        "beats": ["establishing visual of the topic", "illustrative detail shot", "how it affects the customer, hold"],
        "camera": "clean 35mm, slow slides and pans",
        "pacing": "informative",
        "best_for": ["news"],
    },
    {
        "id": "founder_story",
        "name_fa": "داستان بنیان‌گذار",
        "name_en": "Founder story",
        "description_fa": "آدم پشت برند؛ چرا شروع کرد و چه چیزی برایش مهم است.",
        "description_en": "The person behind the brand and why they care.",
        "beats": ["founder at work, thoughtful", "detail of their craft", "founder looks to camera and smiles, hold"],
        "camera": "85mm portrait, warm light, slow push-in",
        "pacing": "calm, emotional",
        "best_for": ["promo"],
    },
    {
        "id": "trend_hook",
        "name_fa": "قلاب ترند (Hook سریع)",
        "name_en": "Fast trend hook",
        "description_fa": "شروع غافلگیرکننده در ۲ ثانیه‌ی اول؛ ریتم سریع برای ریلز.",
        "description_en": "Surprising first 2 seconds, fast rhythm for Reels.",
        "beats": ["unexpected visual hook", "quick reveal of the product", "punchy final pose, hold"],
        "camera": "dynamic 24mm, quick push-ins",
        "pacing": "fast",
        "best_for": ["promo", "sales", "news"],
    },
]

STYLE_BY_ID = {s["id"]: s for s in VIDEO_STYLES}
